"""Turn a copy of the skeleton into a named project. Run once, then delete this file.

    uv run python scripts/rename.py --name my-service --github my-org/my-service

Rewrites the skeleton's placeholder names in every file git would commit, retitles
CONTEXT.md, moves the package directory, and re-locks both uv projects. The AWS account
id and the alert email are not names, and are filled in by hand in infra/config.py.

The placeholders are the skeleton's real names, so the skeleton reads as itself. That
means one string does two jobs: `axiom-maths/python-service-skeleton` in infra/config.py
is the repository the deploy role trusts, and becomes yours; anywhere else it is a
reference back to the template a copy came from, and is left alone.

A rename rather than a template engine, so that the skeleton itself stays a working
project — linted, type-checked, tested and synthesised in CI like any other — instead of
a template that only works once rendered.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
THIS_FILE = Path(__file__).resolve()

UPSTREAM = "axiom-maths/python-service-skeleton"
PLACEHOLDER_NAME = "python-service-skeleton"
PLACEHOLDER_PACKAGE = "python_service_skeleton"

# The one file where UPSTREAM names this repository rather than the template.
IDENTITY = ROOT / "infra" / "config.py"

# Regenerated by `uv lock` afterwards, rather than edited as text.
SKIPPED = {"uv.lock"}

# The glossary keeps the skeleton's terms, which stay true in every project made from
# it, but its title is the skeleton's prose name, which no placeholder matches.
CONTEXT = ROOT / "CONTEXT.md"
CONTEXT_TITLE = "# Python service skeleton\n"

NAME = re.compile(r"^[a-z][a-z0-9]*(-[a-z0-9]+)*$")
GITHUB = re.compile(r"^[A-Za-z0-9-]+/[A-Za-z0-9._-]+$")


def files() -> list[Path]:
    """Every file git would commit: tracked, or untracked and not ignored."""
    listed = subprocess.run(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard", "-z"],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    return [ROOT / path for path in listed.split("\0") if path]


def rename(text: str, name: str, package: str) -> str:
    return text.replace(PLACEHOLDER_NAME, name).replace(PLACEHOLDER_PACKAGE, package)


def main() -> int:
    parser = argparse.ArgumentParser(description=(__doc__ or "").split("\n\n")[0])
    parser.add_argument("--name", required=True, help="project name, e.g. my-service")
    parser.add_argument("--github", required=True, help="owner/repo on GitHub")
    parser.add_argument("--package", help="Python package name (default: from --name)")
    args = parser.parse_args()

    name: str = args.name
    github: str = args.github
    package: str = args.package or name.replace("-", "_")

    if not NAME.match(name):
        parser.error("--name must be lowercase words joined by hyphens")
    if not GITHUB.match(github):
        parser.error("--github must be owner/repo")
    if not package.isidentifier():
        parser.error(f"{package!r} is not a valid Python package name; pass --package")

    old_package_dir = ROOT / "src" / PLACEHOLDER_PACKAGE
    if not old_package_dir.is_dir():
        print("src/ no longer holds the placeholder package: already renamed?", file=sys.stderr)
        return 1

    changed = 0
    for path in files():
        if path == THIS_FILE or path.name in SKIPPED or not path.is_file():
            continue
        try:
            text = path.read_text()
        except UnicodeDecodeError:
            continue
        if path == IDENTITY:
            renamed = rename(text.replace(UPSTREAM, github), name, package)
        else:
            # Rename around each mention of the template, never inside one.
            renamed = UPSTREAM.join(rename(part, name, package) for part in text.split(UPSTREAM))
        if renamed != text:
            path.write_text(renamed)
            changed += 1

    if CONTEXT.is_file() and (text := CONTEXT.read_text()).startswith(CONTEXT_TITLE):
        CONTEXT.write_text(f"# {name}\n" + text.removeprefix(CONTEXT_TITLE))

    old_package_dir.rename(ROOT / "src" / package)

    for project in (ROOT, ROOT / "infra"):
        subprocess.run(["uv", "lock", "--quiet"], cwd=project, check=True)

    print(f"Renamed {changed} files, moved src/{PLACEHOLDER_PACKAGE} to src/{package}.")
    print()
    print("Still to do by hand, in infra/config.py:")
    print("  ACCOUNT      the 12-digit AWS account id")
    print("  ALERT_EMAIL  who the budget and the alarms email")
    print()
    print("Then: make install && make ci, and delete scripts/rename.py.")
    print("Add your domain's terms to CONTEXT.md, under a heading of their own.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
